version: 2.1
orbs:
  node: circleci/node@5.1.1
jobs:
  build-test:
    executor:
      name: node/default
      tag: '21.5'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
      - run:
          command: npm run test
workflows:
  node-tests:
    jobs:
      - build-test
