version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
      - run:
          command: npm run build
workflows:
  node-tests:
    jobs:
      - build-test
